# Logging Configuration
[log]
level = "info" # Logging verbosity (debug, info, warn, error)
logfile = "/var/log/scoreboard.log" # Absolute path to log file
format = "logstash" # Logging format (text, json, logstash)
console_output = false # Enable or disable console log output

# Logstash Configuration
# Only used if log.format is set to "logstash"
[logstash]
type = "scoreboard" # Override logstash type

# Redis Connection Configuration
[redis]
address = "172.17.0.1:6379"  # Address of redis server in host:port format

# Influx DB Connection Configuration
[influxdb]
address = "http://172.17.0.1:8086" # Required Influx DB HTTP API address
db = "soon_fm_scoreboard" # Required DB Name

# HTTP API Configuration
[http]
listen = "0.0.0.0:5000" # Optional listen address, defaults to :5000
