#
# SFM_ 2.0 to 1.0 Legacy Converter Configuration
#

[log]
level = "debug"
logfile = "/var/log/legacy.log"
format = "logstash"

[redis]
host = "127.0.0.1:6379"
topics = [
    "fm:events",
    "player:ready",
    "player:stop",
    "player:stopped",
    "player:play",
    "player:playing",
    "player:resume",
    "player:resumed",
    "player:pause",
    "player:paused",
    "volume:update",
    "volume:updated",
    "volume:mute",
    "volume:muted",
    "volume:unmute",
    "volume:unmuted",
]
